# Generated by Django 5.2.3 on 2025-06-27 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Singer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("img_path", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("info_items", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("img_path", models.CharField(max_length=100)),
                ("lyric", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("info_items", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("singer_name", models.CharField(max_length=100)),
                (
                    "singers",
                    models.ManyToManyField(related_name="songs", to="Music.singer"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("comment_content", models.CharField(max_length=100)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Music.song"
                    ),
                ),
            ],
        ),
    ]
