# Generated by Django 5.2.3 on 2025-07-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singer",
            name="info_items",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="info_items",
            field=models.JSONField(blank=True),
        ),
    ]
